### ISSUE TITLE
Disable image optimization

### ISSUE THREAD

**Issue by srini-leanfolks** [serverless-stack/open-next#15]
I tried to disable the image optimization using this:

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    unoptimized: true
  }
}

module.exports = nextConfig
```

But still I'm getting image-optimization-function folder.

If I don't want it, then how to implement it?

**Comment by khuezy** [comment]
Hi, `images: unoptimized` will only affect the runtime `<Image />` component. OpenNext will currently always build the image optimization resources.

OpenNext can add an option to enable the build, but since this framework is only generating the output files, you can simply ignore it. Or just add a delete command in your build script.

**Comment by srini-leanfolks** [comment]
Ok. Thanks
