### ISSUE TITLE
Add support for geographic location in Middleware

### ISSUE THREAD

**Issue by fwang** [serverless-stack/open-next#24]
Currently in the AWS setup, the middleware function run on viewer request. Unfortunately, [CloudFront does not set geolocation headers for viewer request functions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html#lambda-at-edge-restrictions-cloudfront-headers).
> CloudFront adds the headers after the viewer request event, which means they are not available to Lambda@Edge in a viewer request function.

#### Alternative solution 1:
Run middleware on origin request. This means when the request is cached, middleware won't get run b/c origin request functions don't get called on cached content.

#### Alternative solution 2:
User 2 CloudFront distributions. Run middleware on origin request in the 1st distribution. And the origin for the 1st distribution points to the 2nd distribution. Downside is the added latency.

Suggestions welcome!

**Comment by khuezy** [comment]
In the `NextjsSite`, can you add the `CloudFront-Viewer-Country`, etc... to the `createCloudFrontServerCachePolicy` function for `middleware-function`?

And in `createCloudFrontDistributionForRegional`, can you add this to the serverBehavior origin:
```
customHeaders: { 'x-origin-url': appDomain || fnUrl.url }
```

The Lambda Edge needs to read from the customHeaders field and set the host to that value and set the `x-forwarded-host` to itself. 

ref:
https://github.com/jetbridge/cdk-nextjs/blob/main/assets/lambda%40edge/LambdaOriginRequest.ts#L32
https://github.com/jetbridge/cdk-nextjs/blob/main/src/NextjsDistribution.ts#L306

As for the `middleware.ts` redirects, I'm getting redirected to the raw lambda URL instead of my domain. The `headers.location` is not correctly set. I'm not sure if solving for the above will address the issue.

**Comment by khuezy** [comment]
I've been experimenting w/ latency issues and hacked my way around fixing the latency by moving the server-adapter to `origin-request` edge lambda to the same distribution. Adding option for user to set `edge` mode in `NextjsSite` will kill 2 birds w/ 1 stone: fast latency going from `middleware` to `server` (both using L@E) and gives the server handler access to the geo data.

**Comment by khuezy** [comment]
@fwang This can be closed; the geo data is available now.

**Comment by fwang** [comment]
@khuezy just to clarify, r u accessing the geo data via CloudFront-* headers? Or are they available in NextRequest's geo field (ie. `request.geo.city`)?

**Comment by khuezy** [comment]
@fwang I seen them in the CloudFront-* headers. Vercel has some logic to package that nicely into the `request.geo`, which open-next might want to do.

**Comment by fwang** [comment]
Added in v1.2.0

**Comment by Makisuo** [comment]
Just stumbled on this and it seems like this isn't working anymore. Using SST 3.0.11 geo headers are always empty for me in my next middleware

**Comment by conico974** [comment]
@Makisuo `request.geo` does not work with OpenNext V3 at the moment. I'll add it back in the next releases, but it will require an update in the ion construct as well.
Right now you can use the cloudfront headers https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/adding-cloudfront-headers.html#cloudfront-headers-viewer-location
