### ISSUE TITLE
Suggested fallback for default behaviour causes 403

### ISSUE THREAD

**Issue by jdpst** [serverless-stack/open-next#39]
If a request is made for `mysite.com/some/page/that/does/not/exist` then NextJS will return a 404. The suggested fallback will then cause the request to be sent to S3. However, since there is nothing in S3 either (because the page doesn't exist) then S3 throws a 403.

<img width="922" alt="image" src="https://user-images.githubusercontent.com/63979647/216857628-d754f49b-fc3b-4213-8e78-b6b8c8318188.png">

I understand the theory behind the fallback, but this seems like a very poor tradeoff. Wondering whether anyone has found an elegant way to handle this that allows us to retain the NextJS 404 error page when somebody tries to visit a page that doesn't exist.

For the time being I have stopped redirecting 404s to the S3 origin. 

What would the drawbacks be, if any, to switching the order such that we try to serve from S3 first and only try the lambda if S3 returns a 403? This is the only way I can think of that would end up with the 404 error being handled by NextJS.

Big fan of this project, and the long-form README has been an invaluable resource in getting this working. Thanks!

**Comment by ChadHelbling** [comment]
Ran into a tangental issue and received some context from aws support that explains why this behaves the way it does. Adding here in case it helps anyone.

This is aws' response:
>The error code, 403 Access Denied is returned, instead of 404 Not Found, because when an object does not exist in S3, the system attempts to list the bucket’s contents.  Since that action is not granted in the bucket policy, an Access Denied error is generated.  For security we do not recommend listing that action.

>One additional feature you may want to consider is custom error pages:
(https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/GeneratingCustomErrorResponses.html)
When configured, instead of the viewer receiving the error response, they are redirected to a page you specify.  Often this is the website root with a status code 200.  I just wanted to point them out in case they are helpful.

**Comment by jeffrafter** [comment]
I tried swapping the order of the `/*` group and triggering the fallback on `403`. Good news: it works. Bad news: it is slightly slower. Now for every generic action you are first running it through S3 to look for the file and letting it 403. This will add latency to your site that you really don't need. 

Is it noticeable? Kinda. I tried running page insights before/after and my desktop performance stayed at 100. But my mobile performance dropped from 98 to 95. Not sure how much sense that makes but that was what I experienced. First contentful paint stayed at 0.5s. 

So swapping is probably "good enough."

There are three other options I considered and I thought I would list them here:

1. Add a 404.html to your public folder. Then in CloudFront add a new Error Page Response:

![image](https://user-images.githubusercontent.com/4064/226646632-82038212-5309-424c-86e0-053bf330292a.png)

2. The reason the fallback is there to begin with is because listing all of files in your public folder would exceed the 25 behavior limit (https://github.com/serverless-stack/open-next/blob/main/README.md#workaround-public-static-files-served-by-the-server-function-aws-specific). But by default this deployment solution only has 5 behaviors used (counting the catchall). If you have <= 20 files in your public folder then you could create a behavior for each one and remove the group origin (leaving the `/*` behavior pointing only at the Lambda). You could also get creative and use folders in your `public` like `/images/*` instead of putting things in the root. This would work great until you try to find `/images/that-do-not-exist.png` then you are back to needing something like solution 1.

**Comment by jdpst** [comment]
@jeffrafter we've been running an internal application in production with the switched order and it's been working very well for us. No performance complaints–on the contrary, we were previously using ECS+Fargate so getting _anything_ from the edge locations has been a gain for us.

As you described in your second point, there are also ways to mitigate. We have shuffled around and grouped some of the "unhashed" files in our public folder into a small number of directories which has allowed us to get very close to having a cache behaviour for all "unhashed" files. I think this is something that the README should probably mention as it's definitely a compelling strategy.

<details>
<summary>Our production cache behaviour config</summary>

```ts
        ["/api/*"]: serverFunctionBehaviour,
        ["/_next/data/*"]: serverFunctionBehaviour,
        ["/_next/image"]: imageOptimizationFunctionBehaviour,
        ["/_next/static/*"]: bucketBehaviour,
        ["/assets/*"]: bucketBehaviour,
        ["/fonts/*"]: bucketBehaviour,
        ["/*.png"]: bucketBehaviour,
        ["/*.txt"]: bucketBehaviour,
        ["/*.ico"]: bucketBehaviour,
        ["/*.webmanifest"]: bucketBehaviour,
```

</details>

**Comment by fwang** [comment]
Quick update, we decided to move away from the origin fallback architecture. Instead you should create one cache behavior for each top-level file and folder in the `/public` directory. It's the same setup as @jdpst described above.

Here is the more details about this setup — https://github.com/serverless-stack/open-next#workaround-create-one-cache-behavior-per-top-level-file-and-folder-in-public-aws-specific

^ another reason to not use fallback origin is that it only supports GET requests. So it won't be able to handle server actions requests.

^^ if you are using SST to deploy, update to v2.16.3 and it will use the new architecture.
